services:
  app:
    build:
      context: .
      dockerfile: infra/prod/docker/Dockerfile
    image: skillsherpa-full-stack-take-home-test:latest
    command:
      - bash
      - -c
      - chmod +x /var/www/infra/prod/docker/docker-entrypoint.sh && /var/www/infra/prod/docker/docker-entrypoint.sh
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dbdata:
